### ISSUE TITLE
Wrap Doxygen output in R vignette

### ISSUE THREAD

**Issue by mlysy** [nevrome/rdoxygen#2]
At present, the output lives in `inst/doxygen`, but isn't accessible via a call to `vignette()`.  I've tested a pipeline that does achieve this as follows:

1.  Create e.g., `vignettes/cpp_vignette.Rmd` that does nothing but display an HTML webpage, which in this case should be `inst/doyxgen/html/index.html`.  Essentially this is done with:

    ```yaml
    ---
    pagetitle: "Doxygen Vignette"
    output:
      rmarkdown::html_vignette:
        includes:
          before_body: inst/doxygen/html/index.html
    vignette: >
      %\VignetteIndexEntry{doxygen_vignette}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}
    ---
    ```

    (The path to `index.html` is wrong but hopefully the strategy is clear...)

2.  Unfortunately the approach above fails because `index.html` uses relative links.  So instead of embedding this file directly, I've embedded a file `vignettes/index_redirect.html` which simply redirects to the appropriate page:

    ```html
    <!-- contents of index_redirect.html -->
    <head>
    <meta http-equiv="refresh" content="0; URL=inst/doxygen/html/index.html">
    </head>
    ```

    (Wrong path again, but hopefully strategy is clear.)

3.  Once all this is done, a call to `devtools::build_vignettes()` runs without errors.  However, the call to `vignette("doxygen_vignette")` only works if the entire Doxygen `html` folder gets copied to `inst/doc`.

I would like to write a function `doxy_vignette()` to do all of this in one pass.  Would you consider a PR to this effect?

**Comment by nevrome** [comment]
I'm not sure whether doxygen documentation fits well to the concept of a vignette. One is very technical, the other explicitly designed for human learning. But who am I to decide this? People have written whole research articles in the vignette structure.

I would love to see your idea in action and of course I would consider a PR! Don't forget to add your name to the description as a contributor and write some tests for your function if possible.

**Comment by mlysy** [comment]
> I'm not sure whether doxygen documentation fits well to the concept of a vignette. One is very technical, the other explicitly designed for human learning.

That's an excellent point.  In fact, the Doxygen documentation could be accessed from within R without going through the `vignette()` mechanism via e.g., the command:

```r
utils::browseURL(paste0("file://", 
                        system.file("doxygen", "html", "index.html", package = "MyPackage")))
```

But perhaps the `vignette()` access mechanism is more straightforward, and the Doxygen doc would be available on the CRAN package webpage...

Glad you're willing to consider a PR :)

**Comment by nevrome** [comment]
I understand. The vignette is just there to make the doxygen documentation more visible and more easily accessible. Sounds good!

I'm looking forward to your code!

**Comment by mlysy** [comment]
Please take a look at what I've done in this [fork](https://github.com/mlysy/rdoxygen/tree/doxy-vignettes) (not quite ready for PR yet).  Apart from a few very minor things, all code is under `R/doxy_vignette.R`.

One issue I've yet to resolve is that `vignette()` can *only* load HTML files situated in the `doc` subfolder of an installed package.  Exact error message (displayed in web browser) is:

> Only help files, NEWS, DESCRIPTION and files under doc/ and demo/ in a package can be viewed 

(you can find this string in the body of the unexported function `tools:::httpd`).  However, rdoxygen by default installs Doxygen docs to `myPackage/doxygen`.  I can see two ways around this:

1.  Have `doxy_vignette()` copy the contents of `inst/doxygen` to `inst/doc/doxygen` when building the Doxygen vignette wrapper.

2.  Change the default folder for Doxygen docs to `inst/doc/doxygen`.

It seems to me that the only significant advantage to 1 is perhaps backward compatibility...

How do you suggest we proceed?

**Comment by nevrome** [comment]
Moved discussion to #3
